{
  "spec": {
    "swagger" : "2.0",
    "info" : {
      "title" : "Blue Badge Management Service",
      "description" : "External API for local authorities to manage blue badges",
      "version" : "1.0.0",
      "contact" : {
        "email" : "rob.smallwood@does.not.exist"
      },
      "license" : {
        "name" : "Apache 2.0",
        "url" : "http://www.apache.org/licenses/LICENSE-2.0.html"
      }
    },
    "tags" : [ {
      "name" : "badges",
      "description" : "Badge related operations"
    } ],
    "paths" : {
      "/badges/{badgeNumber}" : {
        "parameters" : [ {
          "$ref" : "#/parameters/BadgeNumberPathParam"
        } ],
        "get" : {
          "tags" : [ "badges" ],
          "summary" : "Retrieve a blue badge given the blue badge number parameter.",
          "operationId" : "retrieveBlueBadge",
          "description" : "Retrieves a blue-badge given the blueBadgeNumber.\n",
          "produces" : [ "application/json" ],
          "responses" : {
            "200" : {
              "description" : "Response when blue badge can be retrieved.\n",
              "schema" : {
                "$ref" : "#/definitions/BadgeResponse"
              }
            },
            "404" : {
              "description" : "A blue badge cannot be found given the parameters specified"
            }
          }
        },
        "delete" : {
          "tags" : [ "badges" ],
          "summary" : "Delete a badge",
          "operationId" : "deleteBlueBadge",
          "description" : "Delete a Blue Badge.",
          "responses" : {
            "200" : {
              "description" : "Deleted."
            }
          }
        }
      },
      "/badges/{badgeNumber}/replacements" : {
        "parameters" : [ {
          "$ref" : "#/parameters/BadgeNumberPathParam"
        } ],
        "post" : {
          "tags" : [ "badges" ],
          "summary" : "Request replacement badge",
          "operationId" : "replaceBlueBadge",
          "description" : "Request a replacement badge.",
          "parameters" : [ {
            "name" : "badgeReplace",
            "in" : "body",
            "schema" : {
              "$ref" : "#/definitions/BadgeReplaceRequest"
            }
          } ],
          "responses" : {
            "200" : {
              "description" : "Badge replacement complete.  New badge number returned.\n",
              "schema" : {
                "$ref" : "#/definitions/BadgeNumberResponse"
              }
            }
          }
        }
      },
      "/badges/{badgeNumber}/cancellations" : {
        "parameters" : [ {
          "$ref" : "#/parameters/BadgeNumberPathParam"
        } ],
        "post" : {
          "tags" : [ "badges" ],
          "summary" : "Request cancel badge",
          "operationId" : "cancelBlueBadge",
          "description" : "Request cancellation of a badge.",
          "parameters" : [ {
            "name" : "badgeCancel",
            "in" : "body",
            "schema" : {
              "$ref" : "#/definitions/BadgeCancelRequest"
            }
          } ],
          "responses" : {
            "200" : {
              "description" : "Badge replacement requested."
            }
          }
        }
      },
      "/badges" : {
        "get" : {
          "tags" : [ "badges" ],
          "summary" : "Find a blue badge given the specified query parameters",
          "operationId" : "findBlueBadge",
          "description" : "By passing in appropriate options, you can search for\navailable badges in the system.  Options are a partial match\nand all submitted options must be matched. At least 1 parameter\nmust be provided.\n",
          "produces" : [ "application/json" ],
          "parameters" : [ {
            "$ref" : "#/parameters/NameParam"
          }, {
            "$ref" : "#/parameters/PostCodeParam"
          } ],
          "responses" : {
            "200" : {
              "description" : "Response when blue badges can (or can not) be found.\n",
              "schema" : {
                "$ref" : "#/definitions/BadgesResponse"
              }
            },
            "default" : {
              "description" : "Unexpected error",
              "schema" : {
                "$ref" : "#/definitions/CommonResponse"
              }
            }
          }
        },
        "post" : {
          "tags" : [ "badges" ],
          "summary" : "Order badges",
          "operationId" : "orderBlueBadges",
          "description" : "Order One or more badges.",
          "produces" : [ "application/json" ],
          "parameters" : [ {
            "name" : "badgeOrder",
            "in" : "body",
            "schema" : {
              "$ref" : "#/definitions/BadgeOrderRequest"
            }
          } ],
          "responses" : {
            "200" : {
              "description" : "Badges created.",
              "schema" : {
                "$ref" : "#/definitions/BadgeNumbersResponse"
              }
            }
          }
        }
      }
    },
    "definitions" : {
      "CommonResponse" : {
        "type" : "object",
        "properties" : {
          "apiVersion" : {
            "type" : "string"
          },
          "context" : {
            "type" : "string"
          },
          "id" : {
            "type" : "string"
          },
          "method" : {
            "type" : "string"
          },
          "error" : {
            "$ref" : "#/definitions/Error"
          }
        }
      },
      "Error" : {
        "type" : "object",
        "properties" : {
          "code" : {
            "type" : "integer"
          },
          "message" : {
            "type" : "string"
          },
          "errors" : {
            "type" : "array",
            "items" : {
              "type" : "object",
              "properties" : {
                "field" : {
                  "type" : "string"
                },
                "reason" : {
                  "type" : "string"
                },
                "message" : {
                  "type" : "string"
                },
                "location" : {
                  "type" : "string"
                },
                "locationType" : {
                  "type" : "string"
                }
              }
            }
          }
        }
      },
      "BadgeNumberResponse" : {
        "description" : "Returns a badge number.",
        "type" : "object",
        "allOf" : [ {
          "$ref" : "#/definitions/CommonResponse"
        }, {
          "type" : "object",
          "properties" : {
            "data" : {
              "type" : "string",
              "example" : "095715",
              "description" : "The unique badge number for this badge"
            }
          }
        } ]
      },
      "BadgeCancelRequest" : {
        "type" : "object",
        "properties" : {
          "badgeNumber" : {
            "type" : "string",
            "example" : "095715",
            "description" : "The unique badge number for this badge"
          },
          "cancelReasonCode" : {
            "type" : "string",
            "maxLength" : 10,
            "description" : "Code for Deceased, No longer needed or Revoked\n"
          }
        },
        "required" : [ "badgeNumber", "cancelReasonCode" ],
        "example" : {
          "badgeNumber" : "72B9HA",
          "cancelReasonCode" : "DECEASED"
        }
      },
      "BadgeReplaceRequest" : {
        "type" : "object",
        "properties" : {
          "badgeNumber" : {
            "type" : "string",
            "example" : "095215",
            "description" : "The unique badge number for this badge"
          },
          "replaceReasonCode" : {
            "type" : "string",
            "maxLength" : 10,
            "description" : "Code for Lost, Stolen or Damaged"
          },
          "deliverToCode" : {
            "type" : "string",
            "maxLength" : 10,
            "description" : "Code for either Home address or LA address"
          },
          "deliveryOptionCode" : {
            "type" : "string",
            "maxLength" : 10,
            "description" : "Code for either Standard or Fast track"
          }
        },
        "required" : [ "badgeNumber", "replaceReasonCode", "deliverToCode", "deliveryOptionCode" ],
        "example" : {
          "badgeNumber" : "72B9HA",
          "replaceReasonCode" : "STOLEN",
          "deliverToCode" : "LA",
          "deliveryOptionCode" : "STANDARD"
        }
      },
      "BadgeNumbersResponse" : {
        "description" : "Contains a list of Badge numbers.",
        "type" : "object",
        "allOf" : [ {
          "$ref" : "#/definitions/CommonResponse"
        }, {
          "type" : "object",
          "properties" : {
            "data" : {
              "type" : "array",
              "items" : {
                "type" : "string",
                "example" : "095215",
                "description" : "The unique badge number for this badge"
              }
            }
          }
        } ]
      },
      "BadgesResponse" : {
        "type" : "object",
        "allOf" : [ {
          "$ref" : "#/definitions/CommonResponse"
        }, {
          "type" : "object",
          "properties" : {
            "data" : {
              "type" : "array",
              "items" : {
                "$ref" : "#/definitions/BadgeSummary"
              }
            }
          }
        } ]
      },
      "BadgeResponse" : {
        "type" : "object",
        "allOf" : [ {
          "$ref" : "#/definitions/CommonResponse"
        }, {
          "type" : "object",
          "properties" : {
            "data" : {
              "$ref" : "#/definitions/Badge"
            }
          }
        } ]
      },
      "BadgeSummary" : {
        "type" : "object",
        "properties" : {
          "badgeNumber" : {
            "type" : "string",
            "description" : "The unique badge number for this badge"
          },
          "partyTypeCode" : {
            "type" : "string"
          },
          "partyTypeDescription" : {
            "type" : "string"
          },
          "name" : {
            "type" : "string",
            "description" : "The name of the badge holder Organisation or Person"
          },
          "nationalInsurance" : {
            "type" : "string",
            "description" : "The badgeholders national insurance number"
          },
          "localAuthorityId" : {
            "type" : "integer"
          },
          "localAuthorityName" : {
            "type" : "string",
            "description" : "Display name of the Local Authority"
          },
          "expiryDate" : {
            "type" : "string",
            "format" : "date",
            "description" : "The date the blue bagde expires"
          },
          "statusCode" : {
            "type" : "string",
            "description" : "The current status of the blue bage"
          },
          "statusDescription" : {
            "type" : "string",
            "description" : "Status full description"
          }
        },
        "example" : {
          "badgeNumber" : "091215",
          "partyTypeCode" : "P",
          "partyTypeDescription" : "Person",
          "name" : "Henry McBoatface",
          "nationalInsurance" : "JL089942B",
          "localAuthorityId" : 2,
          "localAuthorityName" : "Shropshire County Council",
          "expiryDate" : "2019-12-31",
          "statusCode" : "ACTIVE",
          "statusDescription" : "Active"
        }
      },
      "Badge" : {
        "type" : "object",
        "properties" : {
          "badgeNumber" : {
            "type" : "string",
            "example" : "091215",
            "description" : "The unique badge number for this badge"
          },
          "partyTypeCode" : {
            "type" : "string",
            "description" : "Code for Person or Organisation\n"
          },
          "nationalInsurance" : {
            "type" : "string",
            "description" : "The badgeholders national insurance number"
          },
          "name" : {
            "type" : "string",
            "description" : "The name of the badge holder Organisation or Person"
          },
          "homeAddress" : {
            "$ref" : "#/definitions/Address"
          },
          "contactNumber" : {
            "type" : "string"
          },
          "emailAddress" : {
            "type" : "string"
          },
          "dob" : {
            "type" : "string",
            "format" : "date",
            "description" : "The badgeholders date of birth"
          },
          "localAuthorityId" : {
            "type" : "integer",
            "description" : "Id of Local Authority"
          },
          "localAuthorityRef" : {
            "type" : "string"
          },
          "applicationDate" : {
            "type" : "string",
            "format" : "date"
          },
          "applicationSourceCode" : {
            "type" : "string",
            "description" : "Code for Online, Paper, Phone or In person\n"
          },
          "orderDate" : {
            "type" : "string",
            "format" : "date"
          },
          "startDate" : {
            "type" : "string",
            "format" : "date"
          },
          "expiryDate" : {
            "type" : "string",
            "format" : "date",
            "description" : "The date the blue bagde expires"
          },
          "eligibilityCode" : {
            "type" : "string",
            "description" : "Reason for badge"
          },
          "imageLink" : {
            "type" : "string",
            "description" : "Link to photo of badge holder if applicable"
          },
          "statusCode" : {
            "type" : "string",
            "description" : "The current status of the blue bage"
          }
        },
        "example" : {
          "badgeNumber" : "095215",
          "partyTypeCode" : "ORG",
          "nationalInsurance" : "JL089942B",
          "name" : "John Smith",
          "contactNumber" : "01234 567890",
          "emailAddress" : "nodoby@nowhere.com",
          "dob" : "1970-05-29",
          "localAuthorityId" : 2,
          "localAuthorityRef" : "ABCD123",
          "applicationDate" : "2017-11-30",
          "applicationSourceCode" : "ONLINE",
          "orderDate" : "2017-12-18",
          "startDate" : "2018-01-01",
          "expiryDate" : "2019-01-01",
          "eligibilityCode" : "AFCS",
          "imageLink" : "http://adomain.com:1234/myimages?id=hhjjsskkddjj66ssskk",
          "statusCode" : "ACTIVE"
        }
      },
      "BadgeOrderRequest" : {
        "type" : "object",
        "properties" : {
          "partyTypeCode" : {
            "type" : "string",
            "maxLength" : 10,
            "description" : "Code for Person or Organisation\n"
          },
          "nationalInsurance" : {
            "type" : "string",
            "pattern" : "^(?!BG)(?!GB)(?!NK)(?!KN)(?!TN)(?!NT)(?!ZZ)(?:[A-CEGHJ-PR-TW-Z][A-CEGHJ-NPR-TW-Z])(?:\\s*\\d\\s*){6}([A-D]|\\s)$",
            "description" : "The badgeholders national insurance number"
          },
          "name" : {
            "type" : "string",
            "maxLength" : 100,
            "description" : "The name of the badge holder Organisation or Person"
          },
          "homeAddress" : {
            "$ref" : "#/definitions/Address"
          },
          "contactNumber" : {
            "type" : "string",
            "pattern" : "^(((\\+44\\s?\\d{4}|\\(?0\\d{4}\\)?)\\s?\\d{3}\\s?\\d{3})|((\\+44\\s?\\d{3}|\\(?0\\d{3}\\)?)\\s?\\d{3}\\s?\\d{4})|((\\+44\\s?\\d{2}|\\(?0\\d{2}\\)?)\\s?\\d{4}\\s?\\d{4}))(\\s?\\#(\\d{4}|\\d{3}))?$"
          },
          "emailAddress" : {
            "type" : "string",
            "pattern" : "(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|\"(?:[\\x01-\\x08\\x0b\\x0c\\x0e-\\x1f\\x21\\x23-\\x5b\\x5d-\\x7f]|\\\\[\\x01-\\x09\\x0b\\x0c\\x0e-\\x7f])*\")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\\[(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?|[a-z0-9-]*[a-z0-9]:(?:[\\x01-\\x08\\x0b\\x0c\\x0e-\\x1f\\x21-\\x5a\\x53-\\x7f]|\\\\[\\x01-\\x09\\x0b\\x0c\\x0e-\\x7f])+)\\])"
          },
          "dob" : {
            "type" : "string",
            "format" : "date",
            "description" : "The badgeholders date of birth"
          },
          "localAuthorityId" : {
            "type" : "integer",
            "description" : "Id of Local Authority"
          },
          "localAuthorityRef" : {
            "type" : "string",
            "maxLength" : 100
          },
          "applicationDate" : {
            "type" : "string",
            "format" : "date"
          },
          "applicationSourceCode" : {
            "type" : "string",
            "maxLength" : 10,
            "description" : "Code for Online, Paper, Phone or In person\n"
          },
          "startDate" : {
            "type" : "string",
            "format" : "date"
          },
          "expiryDate" : {
            "type" : "string",
            "format" : "date",
            "description" : "The date the blue bagde expires"
          },
          "eligibilityCode" : {
            "type" : "string",
            "maxLength" : 10,
            "description" : "Reason for badge"
          },
          "imageFile" : {
            "type" : "string",
            "format" : "byte",
            "description" : "Base64 encoded image"
          },
          "deliverToCode" : {
            "type" : "string",
            "maxLength" : 10,
            "description" : "Code for either Home address or LA address"
          },
          "deliveryOptionCode" : {
            "type" : "string",
            "maxLength" : 10,
            "description" : "Code for either Standard or Fast track"
          },
          "numberOfBadges" : {
            "type" : "integer",
            "minimum" : 1
          }
        },
        "required" : [ "partyTypeCode", "name", "contactNumber", "localAuthorityId", "startDate", "expiryDate", "applicationDate", "applicationSourceCode", "deliverToCode", "deliveryOptionCode", "numberOfBadges" ],
        "example" : {
          "partyTypeCode" : "PERS",
          "nationalInsurance" : "JL089942B",
          "name" : "John Smith",
          "contactNumber" : "01234 567890",
          "emailAddress" : "nodoby@nowhere.com",
          "dob" : "1970-05-29",
          "localAuthorityId" : 2,
          "localAuthorityRef" : "ABCD123",
          "applicationDate" : "2017-11-30",
          "applicationSourceCode" : "ONLINE",
          "startDate" : "2018-01-01",
          "expiryDate" : "2019-01-01",
          "eligibilityCode" : "AFCS",
          "imageFile" : "AbCdE=",
          "deliverToCode" : "LA",
          "deliveryOptionCode" : "STANDARD",
          "numberOfBadges" : 1
        }
      },
      "Address" : {
        "type" : "object",
        "properties" : {
          "buildingStreet" : {
            "type" : "string",
            "maxLength" : 100,
            "example" : "65 Basil Chambers"
          },
          "line2" : {
            "type" : "string",
            "maxLength" : 100,
            "example" : "Northern Quarter"
          },
          "townCity" : {
            "type" : "string",
            "maxLength" : 100,
            "example" : "Manchester"
          },
          "postCode" : {
            "type" : "string",
            "example" : "SK6 8GH",
            "pattern" : "^((GIR &0AA)|((([A-PR-UWYZ][A-HK-Y]?[0-9][0-9]?)|(([A-PR-UWYZ][0-9][A-HJKSTUW])|([A-PR-UWYZ][A-HK-Y][0-9][ABEHMNPRV-Y]))) &[0-9][ABD-HJLNP-UW-Z]{2}))$"
          }
        },
        "required" : [ "buildingStreet", "townCity", "postCode" ]
      }
    },
    "parameters" : {
      "BadgeNumberParam" : {
        "in" : "query",
        "name" : "badgeNumber",
        "type" : "string",
        "description" : "A valid badge number."
      },
      "BadgeNumberPathParam" : {
        "in" : "path",
        "name" : "badgeNumber",
        "type" : "string",
        "description" : "A valid badge number.",
        "required" : true
      },
      "NameParam" : {
        "in" : "query",
        "name" : "name",
        "type" : "string",
        "description" : "Search the badge holders name"
      },
      "PostCodeParam" : {
        "in" : "query",
        "name" : "postCode",
        "type" : "string",
        "description" : "A valid postcode with or without spaces"
      }
    },
    "host" : "virtserver.swaggerhub.com",
    "basePath" : "/uk-gov-dft/blue-badge/1.0.0",
    "schemes" : [ "https" ]
  },
  "options": {
    "java8" : true,
    "sortParamsByRequiredFlag" : false,
    "modelPackage" : "uk.gov.dft.bluebadge.model.badgemanagement",
    "apiPackage" : "uk.gov.dft.bluebadge.service.badgemanagement.controller",
    "groupId" : "uk.gov.dft.bluebadge",
    "artifactId" : "badge-management-service",
    "artifactVersion" : "1.0.0-SNAPSHOT",
    "sourceFolder" : "generated/src/main/java",
    "dateLibrary" : "java8-localdatetime",
    "delegatePattern" : false,
    "title" : "process-sample",
    "configPackage" : "uk.gov.dft.bluebadge.service.badgemanagement.config.swagger",
    "basePackage" : "uk.gov.dft.bluebadge.dontneed.badgemanagement.application",
    "useBeanValidation" : true,
    "performBeanValidation" : true,
    "useOptional" : false,
    "useTags" : true,
    "hideGenerationTimestamp" : true,
    "appVersion" : "1.0"
  }
}